language: swift
osx_image: xcode10.2

xcode_workspace: KeyedAPIParameters.xcworkspace
xcode_scheme: KeyedAPIParameters
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs

after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'KeyedAPIParameters'
